### ISSUE TITLE
add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [JNSresearcher/SOLVERS_BCGSTAB_GMRES#1]
I suggest adding the topics `bcgstab`, `gmres`, `linear-algebra`, `sparse-linear-algebra` in the About section, as explained at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by JNSresearcher** [comment]
Hello, Beliavsky!

Thank you very much for your attention to my repository.
This is my first experience on GitHub and I plan to continue working with
GitHub.

In the About section I have added the information you recommended:
bicgstab, gmres, linear-algebra, sparse-linear-algebra

Sincerely, JNSResearcher

пн, 1 апр. 2024 г. в 19:40, Beliavsky ***@***.***>:
